name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip]')"
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: make gradlew executable
        run: chmod +x ./gradlew

      - name: get metadata
        id: meta
        run: |
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: build mod
        run: ./gradlew build

      - name: upload artifact (github)
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: build/libs/*all.jar

      - name: send discord embed
        if: success()
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "Spidey Bot",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": "🚀 Build Complete",
              "color": 5814783,

              "author": {
                "name": "By: ${{ github.actor }}",
                "icon_url": "https://github.com/${{ github.actor }}.png"
              },

              "fields": [
                {
                  "name": "Branch",
                  "value": "${{ steps.meta.outputs.branch }}",
                  "inline": true
                },
                {
                  "name": "Commit",
                  "value": "${{ steps.meta.outputs.sha }}",
                  "inline": true
                },
                {
                  "name": "Message",
                  "value": "${{ steps.meta.outputs.msg }}",
                  "inline": false
                }
              ],

              "footer": {
                "text": "GitHub Actions CI"
              },

              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
            }]
          }' \
          $WEBHOOK

      - name: upload jar to discord
        if: success()
        run: |
          curl -F "file=@build/libs/"*.jar ${{ secrets.DISCORD_WEBHOOK }}
